/*
 * FrontEndApi
 * This api is connects the middleware and frontend of a portfolio management web application 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
//
//package edu.albany.icsi418.fa19.teamy.frontend.src.test.java.io.swagger.client.api;
//
//import edu.albany.icsi418.fa19.teamy.frontend.swagger.client.ApiException;
//import edu.albany.icsi418.fa19.teamy.frontend.swagger.client.api.DefaultApi;
//import edu.albany.icsi418.fa19.teamy.frontend.swagger.client.model.Asset;
//import java.math.BigDecimal;
//import edu.albany.icsi418.fa19.teamy.frontend.swagger.client.model.HoldingAsset;
//import org.threeten.bp.OffsetDateTime;
//import edu.albany.icsi418.fa19.teamy.frontend.swagger.client.model.Portfolio;
//import edu.albany.icsi418.fa19.teamy.frontend.swagger.client.model.PortfolioTransaction;
//import edu.albany.icsi418.fa19.teamy.frontend.swagger.client.model.PortfolioTransactionItem;
//import edu.albany.icsi418.fa19.teamy.frontend.swagger.client.model.User;
//import edu.albany.icsi418.fa19.teamy.frontend.swagger.client.model.UserSignup;
//import org.junit.Test;
//import org.junit.Ignore;
//
//import java.util.ArrayList;
//import java.util.HashMap;
//import java.util.List;
//import java.util.Map;
//
///**
// * API tests for DefaultApi
// */
//@Ignore
//public class DefaultApiTest {
//
//    private final DefaultApi api = new DefaultApi();
//
//    /**
//     *
//     *
//     * Search for an asset/assets
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void assetSearchPostTest() throws ApiException {
//        String searchString = null;
//        List<Asset> response = api.assetSearchPost(searchString);
//
//        // TODO: test validations
//    }
//    /**
//     *
//     *
//     * Search for all the assets held by the user
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void holdingAssetSearchPostTest() throws ApiException {
//        Integer portfolioId = null;
//        List<HoldingAsset> response = api.holdingAssetSearchPost(portfolioId);
//
//        // TODO: test validations
//    }
//    /**
//     *
//     *
//     * Add a portfolio to the user profile
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void portfolioAddPostTest() throws ApiException {
//        Integer assertedUser = null;
//        String portfolioName = null;
//        Portfolio response = api.portfolioAddPost(assertedUser, portfolioName);
//
//        // TODO: test validations
//    }
//    /**
//     *
//     *
//     * Deleting a specific portfolio
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void portfolioDeletePostTest() throws ApiException {
//        BigDecimal assertedUser = null;
//        BigDecimal portfolioId = null;
//        api.portfolioDeletePost(assertedUser, portfolioId);
//
//        // TODO: test validations
//    }
//    /**
//     *
//     *
//     * Search for all, or a subset of all portfolios
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void portfolioSearchGetTest() throws ApiException {
//        BigDecimal assertedUser = null;
//        String portfolioName = null;
//        List<Portfolio> response = api.portfolioSearchGet(assertedUser, portfolioName);
//
//        // TODO: test validations
//    }
//    /**
//     *
//     *
//     * Make a new transaction for the portfolio
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void portfolioTransactionAddPostTest() throws ApiException {
//        PortfolioTransactionItem portfolioTransaactionItem = null;
//        api.portfolioTransactionAddPost(portfolioTransaactionItem);
//
//        // TODO: test validations
//    }
//    /**
//     *
//     *
//     * delete a portfolio transaction
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void portfolioTransactionDeletePostTest() throws ApiException {
//        Integer portfolioId = null;
//        api.portfolioTransactionDeletePost(portfolioId);
//
//        // TODO: test validations
//    }
//    /**
//     *
//     *
//     * get the list of transactions related to a portfolio
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void portfolioTransactionSearchGetTest() throws ApiException {
//        Integer portfolioId = null;
//        List<PortfolioTransaction> response = api.portfolioTransactionSearchGet(portfolioId);
//
//        // TODO: test validations
//    }
//    /**
//     *
//     *
//     * Update the asset quatntity in a porfolio transaction/date the asset has been purchased or sold
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void portfolioTransactionUpdatePostTest() throws ApiException {
//        Integer transactionId = null;
//        Double assetQuantity = null;
//        OffsetDateTime newDate = null;
//        api.portfolioTransactionUpdatePost(transactionId, assetQuantity, newDate);
//
//        // TODO: test validations
//    }
//    /**
//     *
//     *
//     * The user deleting their own account or an admin deleting an account
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void userDeletePostTest() throws ApiException {
//        BigDecimal assertedUser = null;
//        BigDecimal id = null;
//        api.userDeletePost(assertedUser, id);
//
//        // TODO: test validations
//    }
//    /**
//     *
//     *
//     * user is required to enter the username and the password to login into the user account
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void userLoginPostTest() throws ApiException {
//        String username = null;
//        String password = null;
//        User response = api.userLoginPost(username, password);
//
//        // TODO: test validations
//    }
//    /**
//     *
//     *
//     * Search for a user/view all the users
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void userSearchGetTest() throws ApiException {
//        BigDecimal assertedUser = null;
//        String email = null;
//        List<User> response = api.userSearchGet(assertedUser, email);
//
//        // TODO: test validations
//    }
//    /**
//     *
//     *
//     * User is required to enter the details necessary to create an account
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void userSignupPostTest() throws ApiException {
//        UserSignup signupForm = null;
//        api.userSignupPost(signupForm);
//
//        // TODO: test validations
//    }
//    /**
//     *
//     *
//     * Update the password of a user
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void userUpdatePasswordPostTest() throws ApiException {
//        BigDecimal assertedUser = null;
//        String oldPassword = null;
//        String newPassword = null;
//        api.userUpdatePasswordPost(assertedUser, oldPassword, newPassword);
//
//        // TODO: test validations
//    }
//}
