/*
 * FrontEndApi
 * This api is connects the middleware and frontend of a portfolio management web application 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package edu.albany.icsi418.fa19.teamy.frontend.swagger.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The role of a user
 */
@JsonAdapter(AccessRole.Adapter.class)
public enum AccessRole {
  USER("USER"),
  SUPPORT("SUPPORT"),
  ADMIN("ADMIN");

  private String value;

  AccessRole(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AccessRole fromValue(String text) {
    for (AccessRole b : AccessRole.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<AccessRole> {
    @Override
    public void write(final JsonWriter jsonWriter, final AccessRole enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AccessRole read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AccessRole.fromValue(String.valueOf(value));
    }
  }
}
