/*
 * FrontEndApi
 * This api is connects the middleware and frontend of a portfolio management web application 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package edu.albany.icsi418.fa19.teamy.frontend.swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Name of asset and its proportion in a portfolio
 */
@Schema(description = "Name of asset and its proportion in a portfolio")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-08T18:15:06.312Z[GMT]")
public class AssetProportion {
  @SerializedName("assetName")
  private String assetName = null;

  @SerializedName("assetQuantityProportion")
  private Double assetQuantityProportion = null;

  @SerializedName("assetNetPriceProportion")
  private Double assetNetPriceProportion = null;

  @SerializedName("assetQuantity")
  private Double assetQuantity = null;

  @SerializedName("assetNetPrice")
  private Double assetNetPrice = null;

  @SerializedName("assetType")
  private String assetType = null;

  @SerializedName("assetTicker")
  private String assetTicker = null;

  public AssetProportion assetName(String assetName) {
    this.assetName = assetName;
    return this;
  }

   /**
   * Get assetName
   * @return assetName
  **/
  @Schema(example = "apple", description = "")
  public String getAssetName() {
    return assetName;
  }

  public void setAssetName(String assetName) {
    this.assetName = assetName;
  }

  public AssetProportion assetQuantityProportion(Double assetQuantityProportion) {
    this.assetQuantityProportion = assetQuantityProportion;
    return this;
  }

   /**
   * Get assetQuantityProportion
   * @return assetQuantityProportion
  **/
  @Schema(example = "3.5", description = "")
  public Double getAssetQuantityProportion() {
    return assetQuantityProportion;
  }

  public void setAssetQuantityProportion(Double assetQuantityProportion) {
    this.assetQuantityProportion = assetQuantityProportion;
  }

  public AssetProportion assetNetPriceProportion(Double assetNetPriceProportion) {
    this.assetNetPriceProportion = assetNetPriceProportion;
    return this;
  }

   /**
   * Get assetNetPriceProportion
   * @return assetNetPriceProportion
  **/
  @Schema(example = "453", description = "")
  public Double getAssetNetPriceProportion() {
    return assetNetPriceProportion;
  }

  public void setAssetNetPriceProportion(Double assetNetPriceProportion) {
    this.assetNetPriceProportion = assetNetPriceProportion;
  }

  public AssetProportion assetQuantity(Double assetQuantity) {
    this.assetQuantity = assetQuantity;
    return this;
  }

   /**
   * Get assetQuantity
   * @return assetQuantity
  **/
  @Schema(example = "3.5", description = "")
  public Double getAssetQuantity() {
    return assetQuantity;
  }

  public void setAssetQuantity(Double assetQuantity) {
    this.assetQuantity = assetQuantity;
  }

  public AssetProportion assetNetPrice(Double assetNetPrice) {
    this.assetNetPrice = assetNetPrice;
    return this;
  }

   /**
   * Get assetNetPrice
   * @return assetNetPrice
  **/
  @Schema(example = "453", description = "")
  public Double getAssetNetPrice() {
    return assetNetPrice;
  }

  public void setAssetNetPrice(Double assetNetPrice) {
    this.assetNetPrice = assetNetPrice;
  }

  public AssetProportion assetType(String assetType) {
    this.assetType = assetType;
    return this;
  }

   /**
   * Get assetType
   * @return assetType
  **/
  @Schema(example = "STOCK", description = "")
  public String getAssetType() {
    return assetType;
  }

  public void setAssetType(String assetType) {
    this.assetType = assetType;
  }

  public AssetProportion assetTicker(String assetTicker) {
    this.assetTicker = assetTicker;
    return this;
  }

   /**
   * Get assetTicker
   * @return assetTicker
  **/
  @Schema(example = "aapl", description = "")
  public String getAssetTicker() {
    return assetTicker;
  }

  public void setAssetTicker(String assetTicker) {
    this.assetTicker = assetTicker;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetProportion assetProportion = (AssetProportion) o;
    return Objects.equals(this.assetName, assetProportion.assetName) &&
        Objects.equals(this.assetQuantityProportion, assetProportion.assetQuantityProportion) &&
        Objects.equals(this.assetNetPriceProportion, assetProportion.assetNetPriceProportion) &&
        Objects.equals(this.assetQuantity, assetProportion.assetQuantity) &&
        Objects.equals(this.assetNetPrice, assetProportion.assetNetPrice) &&
        Objects.equals(this.assetType, assetProportion.assetType) &&
        Objects.equals(this.assetTicker, assetProportion.assetTicker);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetName, assetQuantityProportion, assetNetPriceProportion, assetQuantity, assetNetPrice, assetType, assetTicker);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetProportion {\n");
    
    sb.append("    assetName: ").append(toIndentedString(assetName)).append("\n");
    sb.append("    assetQuantityProportion: ").append(toIndentedString(assetQuantityProportion)).append("\n");
    sb.append("    assetNetPriceProportion: ").append(toIndentedString(assetNetPriceProportion)).append("\n");
    sb.append("    assetQuantity: ").append(toIndentedString(assetQuantity)).append("\n");
    sb.append("    assetNetPrice: ").append(toIndentedString(assetNetPrice)).append("\n");
    sb.append("    assetType: ").append(toIndentedString(assetType)).append("\n");
    sb.append("    assetTicker: ").append(toIndentedString(assetTicker)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
