/*
 * FrontEndApi
 * This api is connects the middleware and frontend of a portfolio management web application 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package edu.albany.icsi418.fa19.teamy.frontend.swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * The data related to the price of an asset
 */
@Schema(description = "The data related to the price of an asset")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-08T18:15:06.312Z[GMT]")
public class AssetPriceDataWithAnalytic {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("assetId")
  private Long assetId = null;

  @SerializedName("dateTime")
  private OffsetDateTime dateTime = null;

  @SerializedName("openPrice")
  private Double openPrice = null;

  @SerializedName("closePrice")
  private Double closePrice = null;

  @SerializedName("highPrice")
  private Double highPrice = null;

  @SerializedName("lowPrice")
  private Double lowPrice = null;

  @SerializedName("adjustedClosePrice")
  private Double adjustedClosePrice = null;

  @SerializedName("percentageGrowth")
  private Double percentageGrowth = null;

  @SerializedName("macdIndex")
  private Double macdIndex = null;

  public AssetPriceDataWithAnalytic id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "1", description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public AssetPriceDataWithAnalytic assetId(Long assetId) {
    this.assetId = assetId;
    return this;
  }

   /**
   * Get assetId
   * @return assetId
  **/
  @Schema(example = "123", description = "")
  public Long getAssetId() {
    return assetId;
  }

  public void setAssetId(Long assetId) {
    this.assetId = assetId;
  }

  public AssetPriceDataWithAnalytic dateTime(OffsetDateTime dateTime) {
    this.dateTime = dateTime;
    return this;
  }

   /**
   * Get dateTime
   * @return dateTime
  **/
  @Schema(description = "")
  public OffsetDateTime getDateTime() {
    return dateTime;
  }

  public void setDateTime(OffsetDateTime dateTime) {
    this.dateTime = dateTime;
  }

  public AssetPriceDataWithAnalytic openPrice(Double openPrice) {
    this.openPrice = openPrice;
    return this;
  }

   /**
   * Get openPrice
   * @return openPrice
  **/
  @Schema(description = "")
  public Double getOpenPrice() {
    return openPrice;
  }

  public void setOpenPrice(Double openPrice) {
    this.openPrice = openPrice;
  }

  public AssetPriceDataWithAnalytic closePrice(Double closePrice) {
    this.closePrice = closePrice;
    return this;
  }

   /**
   * Get closePrice
   * @return closePrice
  **/
  @Schema(description = "")
  public Double getClosePrice() {
    return closePrice;
  }

  public void setClosePrice(Double closePrice) {
    this.closePrice = closePrice;
  }

  public AssetPriceDataWithAnalytic highPrice(Double highPrice) {
    this.highPrice = highPrice;
    return this;
  }

   /**
   * Get highPrice
   * @return highPrice
  **/
  @Schema(description = "")
  public Double getHighPrice() {
    return highPrice;
  }

  public void setHighPrice(Double highPrice) {
    this.highPrice = highPrice;
  }

  public AssetPriceDataWithAnalytic lowPrice(Double lowPrice) {
    this.lowPrice = lowPrice;
    return this;
  }

   /**
   * Get lowPrice
   * @return lowPrice
  **/
  @Schema(description = "")
  public Double getLowPrice() {
    return lowPrice;
  }

  public void setLowPrice(Double lowPrice) {
    this.lowPrice = lowPrice;
  }

  public AssetPriceDataWithAnalytic adjustedClosePrice(Double adjustedClosePrice) {
    this.adjustedClosePrice = adjustedClosePrice;
    return this;
  }

   /**
   * Get adjustedClosePrice
   * @return adjustedClosePrice
  **/
  @Schema(description = "")
  public Double getAdjustedClosePrice() {
    return adjustedClosePrice;
  }

  public void setAdjustedClosePrice(Double adjustedClosePrice) {
    this.adjustedClosePrice = adjustedClosePrice;
  }

  public AssetPriceDataWithAnalytic percentageGrowth(Double percentageGrowth) {
    this.percentageGrowth = percentageGrowth;
    return this;
  }

   /**
   * Get percentageGrowth
   * @return percentageGrowth
  **/
  @Schema(description = "")
  public Double getPercentageGrowth() {
    return percentageGrowth;
  }

  public void setPercentageGrowth(Double percentageGrowth) {
    this.percentageGrowth = percentageGrowth;
  }

  public AssetPriceDataWithAnalytic macdIndex(Double macdIndex) {
    this.macdIndex = macdIndex;
    return this;
  }

   /**
   * Get macdIndex
   * @return macdIndex
  **/
  @Schema(description = "")
  public Double getMacdIndex() {
    return macdIndex;
  }

  public void setMacdIndex(Double macdIndex) {
    this.macdIndex = macdIndex;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetPriceDataWithAnalytic assetPriceDataWithAnalytic = (AssetPriceDataWithAnalytic) o;
    return Objects.equals(this.id, assetPriceDataWithAnalytic.id) &&
        Objects.equals(this.assetId, assetPriceDataWithAnalytic.assetId) &&
        Objects.equals(this.dateTime, assetPriceDataWithAnalytic.dateTime) &&
        Objects.equals(this.openPrice, assetPriceDataWithAnalytic.openPrice) &&
        Objects.equals(this.closePrice, assetPriceDataWithAnalytic.closePrice) &&
        Objects.equals(this.highPrice, assetPriceDataWithAnalytic.highPrice) &&
        Objects.equals(this.lowPrice, assetPriceDataWithAnalytic.lowPrice) &&
        Objects.equals(this.adjustedClosePrice, assetPriceDataWithAnalytic.adjustedClosePrice) &&
        Objects.equals(this.percentageGrowth, assetPriceDataWithAnalytic.percentageGrowth) &&
        Objects.equals(this.macdIndex, assetPriceDataWithAnalytic.macdIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, assetId, dateTime, openPrice, closePrice, highPrice, lowPrice, adjustedClosePrice, percentageGrowth, macdIndex);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetPriceDataWithAnalytic {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    dateTime: ").append(toIndentedString(dateTime)).append("\n");
    sb.append("    openPrice: ").append(toIndentedString(openPrice)).append("\n");
    sb.append("    closePrice: ").append(toIndentedString(closePrice)).append("\n");
    sb.append("    highPrice: ").append(toIndentedString(highPrice)).append("\n");
    sb.append("    lowPrice: ").append(toIndentedString(lowPrice)).append("\n");
    sb.append("    adjustedClosePrice: ").append(toIndentedString(adjustedClosePrice)).append("\n");
    sb.append("    percentageGrowth: ").append(toIndentedString(percentageGrowth)).append("\n");
    sb.append("    macdIndex: ").append(toIndentedString(macdIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
