/*
 * FrontEndApi
 * This api is connects the middleware and frontend of a portfolio management web application 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package edu.albany.icsi418.fa19.teamy.frontend.swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import edu.albany.icsi418.fa19.teamy.frontend.swagger.model.AssetPriceData;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * This the assetPrice over a certain time period
 */
@Schema(description = "This the assetPrice over a certain time period")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-08T18:15:06.312Z[GMT]")
public class AssetPriceOverTime {
  @SerializedName("assetName")
  private String assetName = null;

  @SerializedName("assetId")
  private Long assetId = null;

  @SerializedName("AssetPriceDataList")
  private List<AssetPriceData> assetPriceDataList = null;

  public AssetPriceOverTime assetName(String assetName) {
    this.assetName = assetName;
    return this;
  }

   /**
   * Get assetName
   * @return assetName
  **/
  @Schema(example = "apple", description = "")
  public String getAssetName() {
    return assetName;
  }

  public void setAssetName(String assetName) {
    this.assetName = assetName;
  }

  public AssetPriceOverTime assetId(Long assetId) {
    this.assetId = assetId;
    return this;
  }

   /**
   * Get assetId
   * @return assetId
  **/
  @Schema(description = "")
  public Long getAssetId() {
    return assetId;
  }

  public void setAssetId(Long assetId) {
    this.assetId = assetId;
  }

  public AssetPriceOverTime assetPriceDataList(List<AssetPriceData> assetPriceDataList) {
    this.assetPriceDataList = assetPriceDataList;
    return this;
  }

  public AssetPriceOverTime addAssetPriceDataListItem(AssetPriceData assetPriceDataListItem) {
    if (this.assetPriceDataList == null) {
      this.assetPriceDataList = new ArrayList<AssetPriceData>();
    }
    this.assetPriceDataList.add(assetPriceDataListItem);
    return this;
  }

   /**
   * Get assetPriceDataList
   * @return assetPriceDataList
  **/
  @Schema(description = "")
  public List<AssetPriceData> getAssetPriceDataList() {
    return assetPriceDataList;
  }

  public void setAssetPriceDataList(List<AssetPriceData> assetPriceDataList) {
    this.assetPriceDataList = assetPriceDataList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetPriceOverTime assetPriceOverTime = (AssetPriceOverTime) o;
    return Objects.equals(this.assetName, assetPriceOverTime.assetName) &&
        Objects.equals(this.assetId, assetPriceOverTime.assetId) &&
        Objects.equals(this.assetPriceDataList, assetPriceOverTime.assetPriceDataList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetName, assetId, assetPriceDataList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetPriceOverTime {\n");
    
    sb.append("    assetName: ").append(toIndentedString(assetName)).append("\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    assetPriceDataList: ").append(toIndentedString(assetPriceDataList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
