/*
 * FrontEndApi
 * This api is connects the middleware and frontend of a portfolio management web application 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package edu.albany.icsi418.fa19.teamy.frontend.swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * An asset held by a portfolio
 */
@Schema(description = "An asset held by a portfolio")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-08T18:15:06.312Z[GMT]")
public class HoldingAsset {
  @SerializedName("ownedAssetId")
  private Long ownedAssetId = null;

  @SerializedName("assetName")
  private String assetName = null;

  @SerializedName("assetTicker")
  private String assetTicker = null;

  @SerializedName("assetType")
  private String assetType = null;

  @SerializedName("quantity")
  private Double quantity = null;

  @SerializedName("netValue")
  private Double netValue = null;

  public HoldingAsset ownedAssetId(Long ownedAssetId) {
    this.ownedAssetId = ownedAssetId;
    return this;
  }

   /**
   * Get ownedAssetId
   * @return ownedAssetId
  **/
  @Schema(example = "123", description = "")
  public Long getOwnedAssetId() {
    return ownedAssetId;
  }

  public void setOwnedAssetId(Long ownedAssetId) {
    this.ownedAssetId = ownedAssetId;
  }

  public HoldingAsset assetName(String assetName) {
    this.assetName = assetName;
    return this;
  }

   /**
   * Get assetName
   * @return assetName
  **/
  @Schema(example = "apple", description = "")
  public String getAssetName() {
    return assetName;
  }

  public void setAssetName(String assetName) {
    this.assetName = assetName;
  }

  public HoldingAsset assetTicker(String assetTicker) {
    this.assetTicker = assetTicker;
    return this;
  }

   /**
   * Get assetTicker
   * @return assetTicker
  **/
  @Schema(example = "aapl", description = "")
  public String getAssetTicker() {
    return assetTicker;
  }

  public void setAssetTicker(String assetTicker) {
    this.assetTicker = assetTicker;
  }

  public HoldingAsset assetType(String assetType) {
    this.assetType = assetType;
    return this;
  }

   /**
   * Get assetType
   * @return assetType
  **/
  @Schema(example = "STOCK", description = "")
  public String getAssetType() {
    return assetType;
  }

  public void setAssetType(String assetType) {
    this.assetType = assetType;
  }

  public HoldingAsset quantity(Double quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(example = "3.5", description = "")
  public Double getQuantity() {
    return quantity;
  }

  public void setQuantity(Double quantity) {
    this.quantity = quantity;
  }

  public HoldingAsset netValue(Double netValue) {
    this.netValue = netValue;
    return this;
  }

   /**
   * Get netValue
   * @return netValue
  **/
  @Schema(example = "100", description = "")
  public Double getNetValue() {
    return netValue;
  }

  public void setNetValue(Double netValue) {
    this.netValue = netValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HoldingAsset holdingAsset = (HoldingAsset) o;
    return Objects.equals(this.ownedAssetId, holdingAsset.ownedAssetId) &&
        Objects.equals(this.assetName, holdingAsset.assetName) &&
        Objects.equals(this.assetTicker, holdingAsset.assetTicker) &&
        Objects.equals(this.assetType, holdingAsset.assetType) &&
        Objects.equals(this.quantity, holdingAsset.quantity) &&
        Objects.equals(this.netValue, holdingAsset.netValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ownedAssetId, assetName, assetTicker, assetType, quantity, netValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HoldingAsset {\n");
    
    sb.append("    ownedAssetId: ").append(toIndentedString(ownedAssetId)).append("\n");
    sb.append("    assetName: ").append(toIndentedString(assetName)).append("\n");
    sb.append("    assetTicker: ").append(toIndentedString(assetTicker)).append("\n");
    sb.append("    assetType: ").append(toIndentedString(assetType)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    netValue: ").append(toIndentedString(netValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
