/*
 * FrontEndApi
 * This api is connects the middleware and frontend of a portfolio management web application 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package edu.albany.icsi418.fa19.teamy.frontend.swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import edu.albany.icsi418.fa19.teamy.frontend.swagger.model.PortfolioTransactionType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * filled out PortfolioTransaction details
 */
@Schema(description = "filled out PortfolioTransaction details")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-08T18:15:06.312Z[GMT]")
public class PortfolioTransactionItem {
  @SerializedName("portfolioId")
  private Long portfolioId = null;

  @SerializedName("assetId")
  private Long assetId = null;

  @SerializedName("quantity")
  private Double quantity = null;

  @SerializedName("date")
  private OffsetDateTime date = null;

  @SerializedName("transactionType")
  private PortfolioTransactionType transactionType = null;

  @SerializedName("assetPrice")
  private Double assetPrice = null;

  public PortfolioTransactionItem portfolioId(Long portfolioId) {
    this.portfolioId = portfolioId;
    return this;
  }

   /**
   * The portfolio in which the transaction that occurs
   * @return portfolioId
  **/
  @Schema(example = "12345", description = "The portfolio in which the transaction that occurs")
  public Long getPortfolioId() {
    return portfolioId;
  }

  public void setPortfolioId(Long portfolioId) {
    this.portfolioId = portfolioId;
  }

  public PortfolioTransactionItem assetId(Long assetId) {
    this.assetId = assetId;
    return this;
  }

   /**
   * The Id of the asset which is being bought or sold in the transaction
   * @return assetId
  **/
  @Schema(example = "1", description = "The Id of the asset which is being bought or sold in the transaction")
  public Long getAssetId() {
    return assetId;
  }

  public void setAssetId(Long assetId) {
    this.assetId = assetId;
  }

  public PortfolioTransactionItem quantity(Double quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * The quantity of asset that is being transacted
   * @return quantity
  **/
  @Schema(example = "1.5", description = "The quantity of asset that is being transacted")
  public Double getQuantity() {
    return quantity;
  }

  public void setQuantity(Double quantity) {
    this.quantity = quantity;
  }

  public PortfolioTransactionItem date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * The date on which the transaction will occur
   * @return date
  **/
  @Schema(description = "The date on which the transaction will occur")
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public PortfolioTransactionItem transactionType(PortfolioTransactionType transactionType) {
    this.transactionType = transactionType;
    return this;
  }

   /**
   * Get transactionType
   * @return transactionType
  **/
  @Schema(description = "")
  public PortfolioTransactionType getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(PortfolioTransactionType transactionType) {
    this.transactionType = transactionType;
  }

  public PortfolioTransactionItem assetPrice(Double assetPrice) {
    this.assetPrice = assetPrice;
    return this;
  }

   /**
   * the price of the asset incase a closing price is not provided
   * @return assetPrice
  **/
  @Schema(example = "79.5", description = "the price of the asset incase a closing price is not provided")
  public Double getAssetPrice() {
    return assetPrice;
  }

  public void setAssetPrice(Double assetPrice) {
    this.assetPrice = assetPrice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PortfolioTransactionItem portfolioTransactionItem = (PortfolioTransactionItem) o;
    return Objects.equals(this.portfolioId, portfolioTransactionItem.portfolioId) &&
        Objects.equals(this.assetId, portfolioTransactionItem.assetId) &&
        Objects.equals(this.quantity, portfolioTransactionItem.quantity) &&
        Objects.equals(this.date, portfolioTransactionItem.date) &&
        Objects.equals(this.transactionType, portfolioTransactionItem.transactionType) &&
        Objects.equals(this.assetPrice, portfolioTransactionItem.assetPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(portfolioId, assetId, quantity, date, transactionType, assetPrice);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PortfolioTransactionItem {\n");
    
    sb.append("    portfolioId: ").append(toIndentedString(portfolioId)).append("\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("    assetPrice: ").append(toIndentedString(assetPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
