/*
 * FrontEndApi
 * This api is connects the middleware and frontend of a portfolio management web application 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package edu.albany.icsi418.fa19.teamy.frontend.swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import edu.albany.icsi418.fa19.teamy.frontend.swagger.model.PortfolioRights;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Object that contains a portfolio model and a sharedwith user
 */
@Schema(description = "Object that contains a portfolio model and a sharedwith user")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-08T18:15:06.312Z[GMT]")
public class SharedPortfolio {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("deleted")
  private Boolean deleted = null;

  @SerializedName("ownerUserId")
  private Long ownerUserId = null;

  @SerializedName("ownerEmail")
  private String ownerEmail = null;

  @SerializedName("sharedWithUserEmail")
  private String sharedWithUserEmail = null;

  @SerializedName("portfolioRights")
  private PortfolioRights portfolioRights = null;

  public SharedPortfolio id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Unique Database Primary Key
   * @return id
  **/
  @Schema(example = "1", description = "Unique Database Primary Key")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public SharedPortfolio name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "Portfolio A", description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SharedPortfolio deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @Schema(example = "false", description = "")
  public Boolean isDeleted() {
    return deleted;
  }

  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  public SharedPortfolio ownerUserId(Long ownerUserId) {
    this.ownerUserId = ownerUserId;
    return this;
  }

   /**
   * Get ownerUserId
   * @return ownerUserId
  **/
  @Schema(example = "12345", description = "")
  public Long getOwnerUserId() {
    return ownerUserId;
  }

  public void setOwnerUserId(Long ownerUserId) {
    this.ownerUserId = ownerUserId;
  }

  public SharedPortfolio ownerEmail(String ownerEmail) {
    this.ownerEmail = ownerEmail;
    return this;
  }

   /**
   * Get ownerEmail
   * @return ownerEmail
  **/
  @Schema(example = "Portfolio A", description = "")
  public String getOwnerEmail() {
    return ownerEmail;
  }

  public void setOwnerEmail(String ownerEmail) {
    this.ownerEmail = ownerEmail;
  }

  public SharedPortfolio sharedWithUserEmail(String sharedWithUserEmail) {
    this.sharedWithUserEmail = sharedWithUserEmail;
    return this;
  }

   /**
   * Get sharedWithUserEmail
   * @return sharedWithUserEmail
  **/
  @Schema(example = "sharedwithme@email.com", description = "")
  public String getSharedWithUserEmail() {
    return sharedWithUserEmail;
  }

  public void setSharedWithUserEmail(String sharedWithUserEmail) {
    this.sharedWithUserEmail = sharedWithUserEmail;
  }

  public SharedPortfolio portfolioRights(PortfolioRights portfolioRights) {
    this.portfolioRights = portfolioRights;
    return this;
  }

   /**
   * Get portfolioRights
   * @return portfolioRights
  **/
  @Schema(description = "")
  public PortfolioRights getPortfolioRights() {
    return portfolioRights;
  }

  public void setPortfolioRights(PortfolioRights portfolioRights) {
    this.portfolioRights = portfolioRights;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SharedPortfolio sharedPortfolio = (SharedPortfolio) o;
    return Objects.equals(this.id, sharedPortfolio.id) &&
        Objects.equals(this.name, sharedPortfolio.name) &&
        Objects.equals(this.deleted, sharedPortfolio.deleted) &&
        Objects.equals(this.ownerUserId, sharedPortfolio.ownerUserId) &&
        Objects.equals(this.ownerEmail, sharedPortfolio.ownerEmail) &&
        Objects.equals(this.sharedWithUserEmail, sharedPortfolio.sharedWithUserEmail) &&
        Objects.equals(this.portfolioRights, sharedPortfolio.portfolioRights);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, deleted, ownerUserId, ownerEmail, sharedWithUserEmail, portfolioRights);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SharedPortfolio {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    ownerUserId: ").append(toIndentedString(ownerUserId)).append("\n");
    sb.append("    ownerEmail: ").append(toIndentedString(ownerEmail)).append("\n");
    sb.append("    sharedWithUserEmail: ").append(toIndentedString(sharedWithUserEmail)).append("\n");
    sb.append("    portfolioRights: ").append(toIndentedString(portfolioRights)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
