/*
 * BackEndApi
 * This api is connects the middleware and backend of a portfolio management web application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package edu.albany.icsi418.fa19.teamy.middleware.BackEndClient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import edu.albany.icsi418.fa19.teamy.middleware.BackEndClient.model.AssetPriceData;
import edu.albany.icsi418.fa19.teamy.middleware.BackEndClient.model.Asset;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;
/**
 * The aggregatte values of assets in a portfolio over a time period
 */
@Schema(description = "The aggregatte values of assets in a portfolio over a time period")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-03T01:43:24.217Z[GMT]")
public class AssetAggregateData {
  @SerializedName("portfolioId")
  private Long portfolioId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("startDate")
  private OffsetDateTime startDate = null;

  @SerializedName("endDate")
  private OffsetDateTime endDate = null;

  @SerializedName("assetsInPortfolio")
  private List<Asset> assetsInPortfolio = null;

  @SerializedName("assetValueHashMap")
  private Map<String, List<AssetPriceData>> assetValueHashMap = null;

  public AssetAggregateData portfolioId(Long portfolioId) {
    this.portfolioId = portfolioId;
    return this;
  }

   /**
   * Unique Database Primary Key
   * @return portfolioId
  **/
  @Schema(example = "1", description = "Unique Database Primary Key")
  public Long getPortfolioId() {
    return portfolioId;
  }

  public void setPortfolioId(Long portfolioId) {
    this.portfolioId = portfolioId;
  }

  public AssetAggregateData name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "Portfolio A", description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AssetAggregateData startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @Schema(example = "1996-12-19T16:39:57-08:00", description = "")
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public AssetAggregateData endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @Schema(example = "1996-12-19T16:39:57-08:00", description = "")
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public AssetAggregateData assetsInPortfolio(List<Asset> assetsInPortfolio) {
    this.assetsInPortfolio = assetsInPortfolio;
    return this;
  }

  public AssetAggregateData addAssetsInPortfolioItem(Asset assetsInPortfolioItem) {
    if (this.assetsInPortfolio == null) {
      this.assetsInPortfolio = new ArrayList<Asset>();
    }
    this.assetsInPortfolio.add(assetsInPortfolioItem);
    return this;
  }

   /**
   * The list of assets for which transactions happened in a potfolio
   * @return assetsInPortfolio
  **/
  @Schema(description = "The list of assets for which transactions happened in a potfolio")
  public List<Asset> getAssetsInPortfolio() {
    return assetsInPortfolio;
  }

  public void setAssetsInPortfolio(List<Asset> assetsInPortfolio) {
    this.assetsInPortfolio = assetsInPortfolio;
  }

  public AssetAggregateData assetValueHashMap(Map<String, List<AssetPriceData>> assetValueHashMap) {
    this.assetValueHashMap = assetValueHashMap;
    return this;
  }

  public AssetAggregateData putAssetValueHashMapItem(String key, List<AssetPriceData> assetValueHashMapItem) {
    if (this.assetValueHashMap == null) {
      this.assetValueHashMap = new HashMap<String, List<AssetPriceData>>();
    }
    this.assetValueHashMap.put(key, assetValueHashMapItem);
    return this;
  }

   /**
   * The hashmap with key as assetId and values as an array of pricedata of asset over time
   * @return assetValueHashMap
  **/
  @Schema(description = "The hashmap with key as assetId and values as an array of pricedata of asset over time")
  public Map<String, List<AssetPriceData>> getAssetValueHashMap() {
    return assetValueHashMap;
  }

  public void setAssetValueHashMap(Map<String, List<AssetPriceData>> assetValueHashMap) {
    this.assetValueHashMap = assetValueHashMap;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetAggregateData assetAggregateData = (AssetAggregateData) o;
    return Objects.equals(this.portfolioId, assetAggregateData.portfolioId) &&
        Objects.equals(this.name, assetAggregateData.name) &&
        Objects.equals(this.startDate, assetAggregateData.startDate) &&
        Objects.equals(this.endDate, assetAggregateData.endDate) &&
        Objects.equals(this.assetsInPortfolio, assetAggregateData.assetsInPortfolio) &&
        Objects.equals(this.assetValueHashMap, assetAggregateData.assetValueHashMap);
  }

  @Override
  public int hashCode() {
    return Objects.hash(portfolioId, name, startDate, endDate, assetsInPortfolio, assetValueHashMap);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetAggregateData {\n");
    
    sb.append("    portfolioId: ").append(toIndentedString(portfolioId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    assetsInPortfolio: ").append(toIndentedString(assetsInPortfolio)).append("\n");
    sb.append("    assetValueHashMap: ").append(toIndentedString(assetValueHashMap)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
