/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package edu.albany.icsi418.fa19.teamy.middleware.FrontEndServer.api;

import edu.albany.icsi418.fa19.teamy.middleware.FrontEndServer.model.SharedPortfolio;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-20T03:09:25.605Z[GMT]")
@Api(value = "portfolioShare_search", description = "the portfolioShare_search API")
public interface PortfolioShareSearchApi {

    @ApiOperation(value = "", nickname = "portfolioShareSearchGet", notes = "get the list of portfolios that shared with a user/users to which a portfolio is shared (needs atleast one of the parameters)", response = SharedPortfolio.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Found one or more portfolios shared with the user", response = SharedPortfolio.class, responseContainer = "List"),
        @ApiResponse(code = 404, message = "Record not found in the system"),
        @ApiResponse(code = 500, message = "An error occurred processing this request") })
    @RequestMapping(value = "/portfolioShare_search",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<SharedPortfolio>> portfolioShareSearchGet(@ApiParam(value = "The userid of the user viewing portfolio shared with him/her") @Valid @RequestParam(value = "userId", required = false) Long userId, @ApiParam(value = "The portfolioId of the portfolio that is being shared with another user/users") @Valid @RequestParam(value = "portfolioId", required = false) Long portfolioId);

}
