/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package edu.albany.icsi418.fa19.teamy.middleware.FrontEndServer.api;

import edu.albany.icsi418.fa19.teamy.middleware.FrontEndServer.model.UserSignup;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-20T03:09:25.605Z[GMT]")
@Api(value = "user_signup", description = "the user_signup API")
public interface UserSignupApi {

    @ApiOperation(value = "", nickname = "userSignupPost", notes = "User is required to enter the details necessary to create an account", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Successfully created a new user"),
        @ApiResponse(code = 400, message = "Invalid data provided/Bad request"),
        @ApiResponse(code = 409, message = "Record already exists in the system"),
        @ApiResponse(code = 500, message = "An error occurred processing this request") })
    @RequestMapping(value = "/user_signup",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> userSignupPost(@ApiParam(value = "Filled out user signup form", required = true) @Valid @RequestBody UserSignup body);

}
